// Code generated by sqlc. DO NOT EDIT.
// source: day_students_details.sql

package db

import (
	"context"
)

const getDistinctAcademicYear = `-- name: GetDistinctAcademicYear :many
SELECT DISTINCT academic_year FROM day_students_details
`

func (q *Queries) GetDistinctAcademicYear(ctx context.Context) ([]int16, error) {
	rows, err := q.query(ctx, q.getDistinctAcademicYearStmt, getDistinctAcademicYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var academic_year int16
		if err := rows.Scan(&academic_year); err != nil {
			return nil, err
		}
		items = append(items, academic_year)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
