// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type DayStudentsDetail struct {
	CollegeType                    sql.NullString `json:"college_type"`
	AcademicYear                   int16          `json:"academic_year"`
	Semester                       int16          `json:"semester"`
	SchoolSystem                   sql.NullString `json:"school_system"`
	Departmentgo                   sql.NullString `json:"departmentgo"`
	DepartmentName                 sql.NullString `json:"department_name"`
	Class                          sql.NullString `json:"class"`
	StudentID                      sql.NullString `json:"student_id"`
	ChineseName                    sql.NullString `json:"chinese_name"`
	EnglishName                    sql.NullString `json:"english_name"`
	Gender                         sql.NullString `json:"gender"`
	Country                        sql.NullString `json:"country"`
	Birthday                       sql.NullString `json:"birthday"`
	Birthplace                     sql.NullString `json:"birthplace"`
	NationalIDNumber               sql.NullString `json:"national_id_number"`
	EnrollMethod                   sql.NullString `json:"enroll_method"`
	EnrollmentDate                 sql.NullString `json:"enrollment_date"`
	EnrollmentYear                 int16          `json:"enrollment_year"`
	EnrollmentSemester             int16          `json:"enrollment_semester"`
	GraduationDateBeforeEnrollment sql.NullString `json:"graduation_date_before_enrollment"`
	SchoolGraduated                sql.NullString `json:"school_graduated"`
	DepartmentGraduated            sql.NullString `json:"department_graduated"`
	EducationBackgroundNumber      sql.NullString `json:"education_background_number"`
	MilitaryType                   sql.NullString `json:"military_type"`
	MilitaryServiceClass           sql.NullString `json:"military_service_class"`
	IsOnJob                        sql.NullBool   `json:"is_on_job"`
	Employer                       sql.NullString `json:"employer"`
	JobTitle                       sql.NullString `json:"job_title"`
	ResidencePostalArea            int16          `json:"residence_postal_area"`
	ResidenceAddress               sql.NullString `json:"residence_address"`
	ResidenceTelephone             sql.NullString `json:"residence_telephone"`
	MailingPostalArea              int16          `json:"mailing_postal_area"`
	MailingAddress                 sql.NullString `json:"mailing_address"`
	MailingTelephone               sql.NullString `json:"mailing_telephone"`
	CellPhoneNumber                sql.NullString `json:"cell_phone_number"`
	PersonalEmail                  sql.NullString `json:"personal_email"`
	SchoolEmail                    sql.NullString `json:"school_email"`
	ParentName                     sql.NullString `json:"parent_name"`
	BornYear                       int16          `json:"born_year"`
	Job                            sql.NullString `json:"job"`
	Relationship                   sql.NullString `json:"relationship"`
	ZipCode                        int16          `json:"zip_code"`
	Address                        sql.NullString `json:"address"`
	TelephoneNumber                sql.NullString `json:"telephone_number"`
	IdentityType                   sql.NullString `json:"identity_type"`
	ResidenceCountry               sql.NullString `json:"residence_country"`
	Ethnicity                      sql.NullString `json:"ethnicity"`
	PassportNumber                 sql.NullString `json:"passport_number"`
	ResidencePermitNumber          sql.NullString `json:"residence_permit_number"`
	BloodType                      sql.NullString `json:"blood_type"`
	DisableType                    sql.NullString `json:"disable_type"`
	DisorderLevel                  sql.NullString `json:"disorder_level"`
	HasEnrollTreatment             sql.NullBool   `json:"has_enroll_treatment"`
	Age                            int16          `json:"age"`
	HasCulturalDisadvantage        sql.NullBool   `json:"has_cultural_disadvantage"`
	NewResident                    sql.NullBool   `json:"new_resident"`
	CountryNumber                  sql.NullString `json:"country_number"`
	CountryName                    sql.NullString `json:"country_name"`
	ChildrenOfNewResident          sql.NullString `json:"children_of_new_resident"`
	FatherCountryNumber            sql.NullString `json:"father_country_number"`
	FatherCountryName              sql.NullString `json:"father_country_name"`
	MotherCountryNumber            sql.NullString `json:"mother_country_number"`
	MotherCountryName              sql.NullString `json:"mother_country_name"`
	SpouseCountryNumber            sql.NullString `json:"spouse_country_number"`
	SpouseCountryName              sql.NullString `json:"spouse_country_name"`
	FatherName                     sql.NullString `json:"father_name"`
	FatherBornYear                 int16          `json:"father_born_year"`
	FatherEducationLevel           sql.NullString `json:"father_education_level"`
	FatherTelephoneNumber          sql.NullString `json:"father_telephone_number"`
	FatherOccupation               sql.NullString `json:"father_occupation"`
	FatherEmployer                 sql.NullString `json:"father_employer"`
	MotherName                     sql.NullString `json:"mother_name"`
	MotherBornYear                 int16          `json:"mother_born_year"`
	MotherEducationLevel           sql.NullString `json:"mother_education_level"`
	MotherTelephoneNumber          sql.NullString `json:"mother_telephone_number"`
	MotherOccupation               sql.NullString `json:"mother_occupation"`
	MotherEmployer                 sql.NullString `json:"mother_employer"`
}
